import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// The banner survives minification, so the pointer back to the source repository
	// stays on the shipped file.
	minify: prod,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	// styles.css is hand-edited source and stays readable at the repository root — a
	// dev vault symlinked at the repo reads it directly. The release ships this
	// minified copy instead, uploaded under the plain name esbuild gives it.
	await esbuild.build({
		entryPoints: ["styles.css"],
		outfile: "dist/styles.css",
		minify: true,
		logLevel: "info",
	});
	process.exit(0);
} else {
	await context.watch();
}
