import { ALL_TYPES, BacklogSettings, EXTRA_TYPES, LEVELS, stateMenuValues } from './settings';
import { childTypeChoices, EXTRA_TYPE_RANK, folderForType, LadderPosition } from './itemTypes';
import { ORDER_SPACING } from './writePlan';

/**
 * The README this plugin writes into a backlog folder: what the notes are, which
 * frontmatter carries the hierarchy, and how to write one by hand.
 *
 * Pure text from configuration — it reads no vault and applies nothing, exactly as
 * `writePlan.ts` decides a change without making it. `storage/readmeFile.ts` puts the
 * bytes on disk.
 *
 * Everything it says about *this* backlog is derived rather than retyped: the type
 * table comes from `childTypeChoices`, the property names from the resolved settings,
 * the ranking step from `ORDER_SPACING`, the states from what the view offers. A
 * sentence stating a rule the code does not hold is the one defect this module can
 * ship, so nothing it can compute is written by hand.
 */

/**
 * The file this lands in. Deliberately not `README.md`: a repository root or a docs
 * folder usually already has one, and folder mode reads a note named after its folder
 * as that folder's parent — a name nothing else claims cannot take over either role.
 */
export const README_FILE_NAME = 'README_PRODUCT_BACKLOG.md';

/**
 * How a regeneration recognizes its own output. The whole file is generated, so a
 * hand edit inside it cannot survive; what the marker buys is that a file of the same
 * name this plugin did NOT write is never replaced. It is the first line so a reader
 * meets it before the prose, and an HTML comment so it renders as nothing.
 */
export const README_MARKER = '<!-- Generated by the Product Backlog view. Rewritten in full whenever it is regenerated. -->';

/**
 * Where one offered state came from. Three sources, because the table says so out
 * loud and two of them would be a lie about the vault: a declared state is
 * configuration, an observed one is a value some note carries, and the **offered**
 * one is neither — `stateMenuValues` appends a done value that nothing has used yet,
 * so that marking work done is always reachable.
 */
export type StateSource = 'declared' | 'observed' | 'offered';

/** One state the view offers, and where it came from. */
export interface StateEntry {
	value: string;
	source: StateSource;
}

/**
 * The states this view actually offers, which no single setting holds: the declared
 * workflow, or the observed values standing in for it when nothing is declared — plus
 * the values a declared workflow does not list but notes carry anyway, since
 * `boardColumns` mints a column for each of those and the state menus then offer them.
 */
export function readmeStates(settings: BacklogSettings, observedStates: string[]): StateEntry[] {
	const declared = settings.states.length > 0;
	const seen = new Set(observedStates.map((v) => v.toLowerCase()));
	const source = (value: string): StateSource =>
		declared ? 'declared' : seen.has(value.toLowerCase()) ? 'observed' : 'offered';
	const offered = stateMenuValues(settings, observedStates);
	const entries = offered.map((value) => ({ value, source: source(value) }));
	const known = new Set(offered.map((v) => v.toLowerCase()));
	for (const value of observedStates) {
		if (known.has(value.toLowerCase())) continue;
		known.add(value.toLowerCase());
		entries.push({ value, source: 'observed' });
	}
	return entries;
}

/** How the table names each source — the reader's question is "may I write this?". */
const SOURCE_LABEL: Record<StateSource, string> = {
	declared: 'Declared in the view',
	observed: 'Observed in these notes',
	offered: 'Offered so work can be marked done',
};

/**
 * A value as YAML, quoted when writing it bare would change what it means. The
 * example block is the part a reader copies, so a state called `Needs: review` or
 * `#blocked` has to survive it — bare, those are a mapping and a comment.
 */
function yamlScalar(value: string): string {
	const safe = /^[A-Za-z][A-Za-z0-9 _./-]*$/.test(value) && !/^(true|false|null|yes|no|on|off)$/i.test(value);
	return safe ? value : `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/** Where a type sits on the ladder, for the two questions the type table asks. */
function position(typeName: string): LadderPosition {
	const levelIndex = LEVELS.indexOf(typeName);
	return levelIndex >= 0
		? { levelIndex, effectiveLevelIndex: levelIndex }
		: { levelIndex: -1, effectiveLevelIndex: EXTRA_TYPE_RANK };
}

/** The types a `typeName` item may hold, from the same rule the + button uses. */
const childrenOf = (typeName: string): string[] => childTypeChoices(position(typeName));

/**
 * The types that may hold a `typeName` item — inverted from `childrenOf` rather than
 * stated, so the two halves of the table cannot disagree with each other or with the
 * view. An `Epic` is what `childTypeChoices(null)` offers, so it also reads as a root.
 */
function parentsOf(typeName: string): string[] {
	const parents = ALL_TYPES.filter((candidate) => childrenOf(candidate).includes(typeName));
	return childTypeChoices(null).includes(typeName) ? ['*(nothing — it is a root)*', ...parents] : parents;
}

/**
 * A value as an inline code span. Property names, states and folders are all user
 * data, so the fence is as long as it has to be and a value that begins or ends with
 * a backtick gets the padding spaces CommonMark strips again — a state called
 * `` `todo` `` must render as itself rather than closing the span early.
 */
function code(value: string): string {
	const longest = Math.max(0, ...[...value.matchAll(/`+/g)].map((m) => m[0].length));
	const fence = '`'.repeat(longest + 1);
	const pad = value.startsWith('`') || value.endsWith('`') ? ' ' : '';
	return `${fence}${pad}${value}${pad}${fence}`;
}

/**
 * The same, inside a table cell — where a pipe ends the cell whatever it sits in,
 * code span included, and has to be escaped before the row is parsed. A state named
 * `Waiting | external` otherwise silently becomes two columns.
 */
const cell = (value: string): string => code(value).replace(/\|/g, '\\|');

const list = (values: string[]): string =>
	values.length > 0 ? values.map((v) => (v.startsWith('*') ? v : cell(v))).join(', ') : '*(nothing)*';

function typeSection(): string[] {
	const rows = ALL_TYPES.map((t) => `| ${cell(t)} | ${list(parentsOf(t))} | ${list(childrenOf(t))} |`);
	return [
		'## The item types',
		'',
		`${LEVELS.join(' → ')} is a ladder: each level holds the next one down. ` +
			`${EXTRA_TYPES.join(' and ')} sit *beside* it — they hang from any rung above the ` +
			`deepest and hold ${code(LEVELS[LEVELS.length - 1])} items wherever they hang, which ` +
			'is why they are types rather than levels.',
		'',
		'| Type | Parent may be | Children may be |',
		'| --- | --- | --- |',
		...rows,
		'',
		'Write the type exactly as spelled above; matching is case-insensitive but the ' +
			'spelling is the vocabulary. A type this plugin does not ship is kept as written and ' +
			'shown as itself — it is never rewritten into one of these.',
	];
}

function fieldRows(settings: BacklogSettings): string[] {
	const rows = [
		`| ${cell(settings.parentKey)} | Every item except a root | A link to the parent note: ${code('"[[Note name]]"')}. Quote it, or YAML reads the brackets as a list. Present but empty means the top level |`,
		`| ${cell(settings.orderKey)} | Every item | A number. The rank among the notes sharing a parent — see below |`,
		`| ${cell(settings.typeKey)} | Every item | One of the type names above |`,
	];
	if (settings.stateKey) rows.push(`| ${cell(settings.stateKey)} | Optional | The workflow state — see below |`);
	if (settings.tagsKey) rows.push(`| ${cell(settings.tagsKey)} | Optional | Tags, as a YAML list or one string |`);
	if (settings.horizonKey) rows.push(`| ${cell(settings.horizonKey)} | Optional | Which planning horizon the item sits in |`);
	if (settings.startKey) rows.push(`| ${cell(settings.startKey)} | Optional | Planned start, ${code('YYYY-MM-DD')} |`);
	if (settings.targetKey) rows.push(`| ${cell(settings.targetKey)} | Optional | Planned target, ${code('YYYY-MM-DD')} |`);
	return rows;
}

function propertySection(settings: BacklogSettings): string[] {
	return [
		'## The properties that carry the hierarchy',
		'',
		'These are the keys **this** backlog uses. They are configurable per view, so they ' +
			'are read out of the configuration rather than assumed.',
		'',
		'| Property | On | Holds |',
		'| --- | --- | --- |',
		...fieldRows(settings),
		'',
		`The parent link is read generously: ${code('"[[Note name]]"')}, a bare note name, an ` +
			`alias (${code('"[[Note name|what it reads as]]"')}) and a YAML list whose first entry ` +
			'is any of those all resolve to the same note. A link that resolves to nothing leaves ' +
			'the item where it is rather than dropping it. Numbers may be written as strings.',
		'',
		settings.folderHierarchy
			? `A key with **no value** — ${code(`${settings.parentKey}:`)} and nothing after it — is not ` +
				'the same as no key at all, and in this view the difference decides the tree: an ' +
				'empty value pins the note to the top level, while omitting the key lets the folder ' +
				'note above it become the parent. That is also what this plugin writes when it moves ' +
				'something to the top.'
			: `A key with **no value** — ${code(`${settings.parentKey}:`)} and nothing after it — reads ` +
				'as the top level, which is what this plugin writes when it moves something there. ' +
				'Omitting the key entirely means the same thing here.',
		'',
		settings.hierarchyOnly
			? 'A note in this folder joins the backlog when it declares one of the types **listed ' +
				'above**, or has a parent. A type of your own is kept and shown, but it does not by ' +
				'itself enrol a note that has no parent — give such a note a parent, or it stays out ' +
				'of the tree. Declare neither and it stays an ordinary note, which is how a document ' +
				'like this one sits here without becoming a work item.'
			: 'This view treats **every** note it returns as an item, so a note with none of these ' +
				'properties still appears, at the top level and untyped.',
	];
}

function rankingSection(settings: BacklogSettings): string[] {
	return [
		'## Ranking',
		'',
		`${code(settings.orderKey)} ranks an item among the notes that share its parent — lowest ` +
			`first. Nothing is global: the same number under two different parents is two ` +
			`unrelated ranks. The view writes them ${ORDER_SPACING} apart, leaving room to insert ` +
			'without renumbering, and renumbers a group only when a move needs it.',
		'',
		'Two siblings may end up sharing a number, and an item may carry none at all. Nothing ' +
			'breaks: the tie is settled by the order the base itself returned them in — whatever ' +
			'sort is configured in the Bases toolbar, file name by default — and items without a ' +
			'number sort last. That means the tie-break is a view setting rather than a property ' +
			'of these notes, so give siblings distinct numbers when writing by hand.',
	];
}

/**
 * The done values this workflow does not offer. Writing one still finishes an item —
 * `doneValues` is what the model matches, whatever the state list says — so a reader
 * whose workflow omits `Done` has to be told that writing it anyway means done.
 */
function unlistedDone(settings: BacklogSettings, states: StateEntry[]): string[] {
	const listed = new Set(states.map((s) => s.value.toLowerCase()));
	const missing = settings.doneValues.filter((v) => v && !listed.has(v.toLowerCase()));
	if (missing.length === 0) return [];
	return [
		'',
		`${missing.map(code).join(', ')} ${missing.length === 1 ? 'is' : 'are'} not offered as ` +
			`${missing.length === 1 ? 'a state' : 'states'} here, but ${missing.length === 1 ? 'it counts' : 'they count'} ` +
			'as done wherever written: what makes an item finished is this list, not the workflow above.',
	];
}

function stateSection(settings: BacklogSettings, states: StateEntry[]): string[] {
	if (!settings.stateKey || states.length === 0) return [];
	const done = new Set(settings.doneValues.map((v) => v.toLowerCase()));
	const rows = states.map(
		(s) => `| ${cell(s.value)} | ${done.has(s.value.toLowerCase()) ? 'Yes' : 'No'} | ${SOURCE_LABEL[s.source]} |`,
	);
	return [
		'## Workflow states',
		'',
		`${code(settings.stateKey)} holds the state. Matching is case-insensitive.`,
		'',
		'| State | Counts as done | Where it comes from |',
		'| --- | --- | --- |',
		...rows,
		'',
		states.some((s) => s.source !== 'declared')
			? 'The states marked observed are not configured anywhere — they are simply the values ' +
				'these notes carry, so a new one written here becomes a state this backlog has.'
			: 'These are the declared states. A value outside the list still shows, in a column of ' +
				'its own, so nothing is lost by writing one — it just sits outside the workflow.',
		// Done-matching runs against the configured values, not against the workflow, so a
		// value missing from the table above still finishes an item — silently, from the
		// reader's point of view, since nothing else here would have mentioned it.
		...unlistedDone(settings, states),
	];
}

function planningSection(settings: BacklogSettings): string[] {
	const lines: string[] = [];
	if (settings.horizonKey && settings.horizonValues.length > 0) {
		lines.push(
			`${code(settings.horizonKey)} places an item in a planning horizon: ` +
				`${settings.horizonValues.map(code).join(', ')}. A value outside that list is not ` +
				'lost and not guessed at — it gets a horizon of its own, after the declared ones, ' +
				'the same way a state nobody declared still gets a column. What is set aside is an ' +
				'item with no value at all, or one written in a way the reader cannot make a ' +
				'horizon of.',
		);
	}
	// Either key alone is a configured axis — a milestone-only roadmap is coherent, and
	// `configuredAxes` says so — and a view with one would otherwise get no section at all.
	const dateKeys = [settings.startKey, settings.targetKey].filter(Boolean);
	if (dateKeys.length === 2) {
		lines.push(
			`${code(settings.startKey)} and ${code(settings.targetKey)} are the planned dates, ` +
				`written ${code('YYYY-MM-DD')}. An item stating only one of the two is a milestone on ` +
				'that date; a target earlier than its start is set aside rather than drawn backwards.',
		);
	} else if (dateKeys.length === 1) {
		lines.push(
			`${code(dateKeys[0])} is the planned date, written ${code('YYYY-MM-DD')}. It is the only ` +
				'date property configured here, so every item that states one is drawn as a ' +
				'milestone rather than as a span.',
		);
	}
	if (lines.length > 0) {
		lines.push(
			'These are a **plan**, and the only things that write them are you and the view\'s own ' +
				'placement actions — Set horizon and Clear horizon, Schedule and Unschedule, each ' +
				'writing or removing exactly the keys named here. Nothing writes them as a side ' +
				'effect of a move, a state change or a rename.',
		);
	}
	return lines.length > 0 ? ['## Planning', '', ...lines.flatMap((l) => [l, ''])].slice(0, -1) : [];
}

function filingSection(settings: BacklogSettings): string[] {
	const configured = ALL_TYPES.map((t) => ({ type: t, folder: folderForType(t, settings) })).filter((e) => e.folder);
	const rows = configured.map((e) => `| ${cell(e.type)} | ${cell(e.folder ?? '')} |`);
	return [
		'## Where notes are filed',
		'',
		settings.folderHierarchy
			? 'In this view folders are **also** hierarchy: a note with no parent property hangs ' +
				'from the nearest folder note above it, so moving such a note moves it in the tree. ' +
				'A note that names its parent is unaffected — the property always wins — which is ' +
				'the way to file a note anywhere and keep its place. Below is where this view puts ' +
				'a note it creates, in this order:'
			: 'Folders are filing, not hierarchy: the tree comes from the properties above, so a ' +
				'note is in the right place wherever it lives. What follows is only where **this** ' +
				'view puts a note it creates, in this order:',
		'',
		...(settings.folderHierarchy
			? [
					'1. Beside the parent\'s folder note — this view infers hierarchy from folders, ' +
						'so that placement is meaningful here. Skipped when the parent is a note the ' +
						'view is showing from outside its own filter.',
				]
			: []),
		`${settings.folderHierarchy ? '2' : '1'}. The folder configured for the type, when it has one.`,
		`${settings.folderHierarchy ? '3' : '2'}. ${settings.homeFolder ? `The home folder, ${code(settings.homeFolder)}.` : 'The home folder, which is not configured here.'}`,
		`${settings.folderHierarchy ? '4' : '3'}. Wherever most of the existing items already live.`,
		...(rows.length > 0 ? ['', '| Type | Folder |', '| --- | --- |', ...rows] : []),
	];
}

function exampleSection(settings: BacklogSettings, states: StateEntry[]): string[] {
	const feature = LEVELS[Math.min(1, LEVELS.length - 1)];
	const child = LEVELS[Math.min(2, LEVELS.length - 1)];
	// Keys are configurable and therefore user data too: one containing a colon would
	// turn the line a reader copies into a different mapping, or into nothing valid.
	const entry = (key: string, value: string): string => `${yamlScalar(key)}: ${value}`;
	const lines = [
		'---',
		entry(settings.typeKey, child),
		entry(settings.parentKey, '"[[Checkout redesign]]"'),
		entry(settings.orderKey, String(ORDER_SPACING * 2)),
	];
	if (settings.stateKey && states.length > 0) lines.push(entry(settings.stateKey, yamlScalar(states[0].value)));
	lines.push('---', '', `# Pay with a saved card`, '', 'Whatever the note is about.');
	return [
		'## A note, written by hand',
		'',
		`A ${code(child)} under a ${code(feature)} called *Checkout redesign*, second among its ` +
			'siblings. Nothing else is needed — the view fills in what it writes itself.',
		'',
		'```markdown',
		...lines,
		'```',
	];
}

function rulesSection(settings: BacklogSettings): string[] {
	return [
		'## What the view will and will not do to these notes',
		'',
		'- **The type rules are advisory.** They decide what the view *offers*; nothing is ' +
			`refused, and a type you declare is the type you keep: a ${code(LEVELS[LEVELS.length - 1])} ` +
			`under an ${code(LEVELS[0])} stays one, at its own level, however oddly it sits. Only a ` +
			'note with **no** type takes the level its position implies, and a type this plugin ' +
			'does not ship sits one rung below its parent so its own children continue the ladder.' +
			`${settings.autoType ? ' In this view a move does re-type what it moves, to match where it lands.' : ' Moving a note never rewrites its type.'}`,
		'- **Only the properties above are written.** Prose, headings and any other frontmatter ' +
			'are left alone.',
		'- **Levels, progress and board position are derived, never stored.** Do not write them ' +
			'back: they are computed from the properties above every time the view opens.',
		'- **A note nothing links to is still a note.** An unresolved parent leaves the item at ' +
			'the top level rather than hiding it.',
	];
}

/**
 * The whole document. Deterministic in its inputs — same settings and states in, same
 * bytes out — so a regeneration that changes nothing can be recognized as a no-op and
 * a repository gets no diff for running the command twice.
 */
export function backlogReadmeContent(settings: BacklogSettings, observedStates: string[]): string {
	const states = readmeStates(settings, observedStates);
	const sections = [
		[
			README_MARKER,
			'',
			'# This folder is a product backlog',
			'',
			'A note here becomes a work item by carrying the properties below — the folder does ' +
				'not make it one, and notes that carry none of them stay ordinary notes. The ' +
				'hierarchy between the items lives in frontmatter rather than in folders, on ' +
				'purpose: they stay plain markdown, so they can be read, written and reviewed in ' +
				'any editor, with or without Obsidian and the Product Backlog view that generated ' +
				'this file.',
			'',
			'This document is generated from that view\'s configuration, so the property names ' +
				'below are the ones this backlog actually uses.',
		],
		typeSection(),
		propertySection(settings),
		rankingSection(settings),
		stateSection(settings, states),
		planningSection(settings),
		filingSection(settings),
		exampleSection(settings, states),
		rulesSection(settings),
	].filter((s) => s.length > 0);
	return sections.map((s) => s.join('\n')).join('\n\n') + '\n';
}
