/**
 * Which file the generated README is, and how it says who generated it.
 *
 * Its own module because it is its own question: `backlogReadme.ts` decides what the
 * document SAYS, and this decides what the document IS — the name nothing else claims,
 * and the one line `storage/readmeFile.ts` reads to answer "may I replace this?". The
 * writer needs the second without the first, and the split is what keeps a rule about
 * identity from being read out of four hundred lines of prose.
 */

/**
 * The file this lands in. Deliberately not `README.md`: a repository root or a docs
 * folder usually already has one, and folder mode reads a note named after its folder
 * as that folder's parent — a name nothing else claims cannot take over either role.
 */
export const README_FILE_NAME = 'README_PRODUCT_BACKLOG.md';

/**
 * How a regeneration recognizes its own output. The whole file is generated, so a
 * hand edit inside it cannot survive; what the marker buys is that a file of the same
 * name this plugin did NOT write is never replaced. It is the first line so a reader
 * meets it before the prose, and an HTML comment so it renders as nothing.
 */
export const README_MARKER_PREFIX = '<!-- Generated by the Product Backlog view';

/**
 * The characters an HTML comment cannot carry, escaped so that escaping loses nothing:
 * `>` cannot appear at all and `--` would end the comment early, and a source is user
 * data that may hold either. Percent escapes rather than removal, because the line is
 * an identity two views are compared by — `Product--Backlog.base` and
 * `Product-Backlog.base` are two different bases, and flattening them to one marker
 * makes a view read the other's file as its own and report "Updated" for a contract it
 * just overwrote. The same reasoning percent-encodes both halves of the collapse
 * store's key.
 *
 * `%` is escaped first and unconditionally, which is what makes the mapping injective:
 * every `%25`, `%2D`, `%3C` or `%3E` left in the line was written by this function, so
 * a source that literally spells `%2D` comes back spelling it. Only a hyphen that would
 * *form* a run is escaped, so an ordinary `work/Product-Backlog.base` still reads as
 * itself in a file a human opens.
 */
function encodeSource(source: string): string {
	return source
		.replace(/%/g, '%25')
		.replace(/</g, '%3C')
		.replace(/>/g, '%3E')
		// A line break is the one character that would cost the marker its whole job: the
		// reader only ever sees the FIRST line, so a view name holding one — a hand-edited
		// `.base` can spell it — would leave every regeneration reading a truncated marker
		// and calling this plugin's own document somebody else's.
		.replace(/\r/g, '%0D')
		.replace(/\n/g, '%0A')
		.replace(/-(?=-)/g, '%2D');
}

/** Its exact inverse: one left-to-right pass, so an escaped `%` never re-escapes. */
const decodeSource = (encoded: string): string =>
	encoded.replace(/%(0A|0D|25|2D|3C|3E)/g, (_, hex: string) => String.fromCharCode(parseInt(hex, 16)));

/**
 * The two halves the encoded source sits between, spelled once because `readmeSource`
 * is the exact inverse of `readmeMarker` only while both read the same text. Written
 * twice, the writer could drift and leave the reader accepting a line nothing produces.
 */
const MARKER_OPEN = `${README_MARKER_PREFIX} from "`;
const MARKER_CLOSE = '". Rewritten in full whenever it is regenerated. -->';

/**
 * The marker, naming the view it came from. Two views may share a home folder while
 * configuring different property keys, and a folder cannot have two contracts: without
 * the source in the line, each view reads the other's file as its own and replaces it,
 * reporting nothing but "Updated". Written so a mismatch is *visible* — to the code
 * that refuses it, and to whoever opens the file.
 */
export function readmeMarker(source: string): string {
	return `${MARKER_OPEN}${encodeSource(source)}${MARKER_CLOSE}`;
}

/**
 * The view a generated file names, or null when the line is not one of ours.
 *
 * Read rather than compared, because the identity is **reported, never enforced**: a
 * base path and a view name are both things a user renames, and refusing a mismatch
 * would leave a view unable to refresh its own document after an ordinary rename —
 * a false refusal, found by someone who was doing something else, in exchange for
 * catching a case where the honest fix is to tell them what they just replaced.
 *
 * Decoded, because what comes back is shown to a user in a notice; the comparison it
 * feeds is unaffected either way, the encoding being injective.
 *
 * The WHOLE line has to match, both halves, because this answers a second question its
 * caller acts on: a file whose first line parses is a file the plugin may replace
 * wholesale. Validating the opening alone would accept a line truncated after the
 * source — a half-written marker from an interrupted write is the file least able to
 * afford being overwritten — and a comment somebody wrote themselves that happens to
 * start the same way. Between the two halves everything is the source, unambiguously:
 * `encodeSource` leaves no `>` in it, so the closing `-->` can only be the one this
 * module wrote.
 */
export function readmeSource(line: string): string | null {
	const trimmed = line.trimEnd();
	if (!trimmed.startsWith(MARKER_OPEN) || !trimmed.endsWith(MARKER_CLOSE)) return null;
	const encoded = trimmed.slice(MARKER_OPEN.length, trimmed.length - MARKER_CLOSE.length);
	const source = decodeSource(encoded);
	// The interior has to be something `encodeSource` would have PRODUCED, not merely
	// something `decodeSource` can read: a raw `>` or `--` in there is a line this module
	// cannot have written, so a hand-written comment that copies both halves around one
	// is somebody's own file — and answering "ours" hands the whole of it to the writer.
	// Re-encoding is the check because the mapping is injective: canonical text is its own
	// round trip, and nothing else is.
	return encodeSource(source) === encoded ? source : null;
}

/** The separator between the two halves of a source, and its escape. */
const SOURCE_SEPARATOR = ' › ';
const SEPARATOR_ESCAPE = '%E2%80%BA';

/**
 * The two halves of a source, joined so the join can be undone. A base path and a view
 * name are both free text, and a view called `b.base › c` under base `a.base` would
 * otherwise produce the same line as view `c` under a base called `a.base › b.base` —
 * two different views answering to one identity, so the second replaces the first's
 * document and is reported as an ordinary update.
 *
 * `%` first, then the separator, which is the same trick `encodeSource` plays and for
 * the same reason: escaping the escape character is what makes the mapping injective.
 * Nothing but `displaySource` undoes it — the comparison needs the escaped form, and a
 * notice needs the name as the user spelled it.
 */
export function joinSource(base: string, view: string): string {
	const part = (text: string): string => text.replace(/%/g, '%25').replace(/›/g, SEPARATOR_ESCAPE);
	return `${part(base)}${SOURCE_SEPARATOR}${part(view)}`;
}

/**
 * A source as the user spells it, for showing in a notice. The escaping above exists to
 * keep two identities apart, and telling somebody their base is called `work/100%25.base`
 * is the escaping leaking out of the question it answers.
 *
 * One left-to-right pass, so an escaped `%` never decodes twice, and the separator itself
 * is left alone: it is a literal, not an escape.
 */
export const displaySource = (source: string): string =>
	source.replace(/%(25|E2%80%BA)/g, (_, code: string) => (code === '25' ? '%' : '›'));
