// @vitest-environment jsdom
import { beforeEach, describe, expect, it } from 'vitest';
import { Modal, Notice } from '../../helpers/obsidian-mock';
import { button, emptyReleaseVault, releaseScreen, scopeVault } from '../../helpers/release';
import { FakeVault } from '../../helpers/vault';
import { flush } from '../../helpers/view';
import { joinSource, readmeMarker } from '../../../src/domain/readmeMarker';
import { en } from '../../../src/i18n/en';

beforeEach(() => {
	document.body.empty();
	Modal.forget();
	Notice.reset();
});

const NOTES = 'notes/0.9 release notes.md';
const NOTES_ON = { releaseNotesFolder: 'notes' };

/** The marker a file generated by this view for the release at `path` carries.
 *  `Releases.base` and `Releases` are what the harness's own leaf gives it. */
const markerFor = (path: string): string => readmeMarker(joinSource('Releases.base', 'Releases', path));

const lastNotice = (): string => Notice.messages[Notice.messages.length - 1] ?? '';

async function press(view: Parameters<typeof button>[0], selector: string): Promise<void> {
	button(view, selector).click();
	await flush();
}

/** Two releases whose basenames are the same and whose paths are not — which Obsidian
 *  allows and the OUTPUT path cannot tell apart, since it is built from the basename. */
function twoReleasesOneBasename(): FakeVault {
	const vault = new FakeVault();
	vault.addFile('a/0.9.md', { frontmatter: { type: 'Release', version: '0.9.0', status: 'Released' } });
	vault.addFile('A member.md', { frontmatter: { type: 'PBI', release: '[[a/0.9]]' } });
	return vault;
}

describe('generating the release notes', () => {
	it('is withheld inside an embedded base, which cannot name its own output', async () => {
		// `resolveViewIdentity` returns null for an embedded base DELIBERATELY: every base
		// embedded in one note is drawn in that note's leaf, so any identity built from it
		// is one they all share. The marker needs a unique one, and two such views with the
		// same view name, notes folder and release would each read the other's file as
		// their own to replace — the identity collision defeating the refusal rather than
		// tripping it. So the control is absent and says why.
		const { view, vault } = releaseScreen({ status: 'Released' }, scopeVault(), NOTES_ON, { embedded: true });
		expect(view.viewEl.querySelector('.pbl-rel-notes')).toBeNull();
		expect(view.viewEl.textContent).toContain(en['release.notes.embedded']);
		expect(vault.contents.get(NOTES)).toBeUndefined();
	});

	it('writes the notes, and opens them', async () => {
		const vault = scopeVault();
		vault.addFile('First PBI.md', { frontmatter: { type: 'PBI', release: '[[0.9]]', order: 1 } });
		const { view } = releaseScreen({ status: 'Released' }, vault, NOTES_ON);

		await press(view, '.pbl-rel-notes');

		expect(vault.contents.get(NOTES)).toContain('First PBI');
		expect(vault.opened.map((o) => o.path)).toEqual([NOTES]);
		expect(lastNotice()).toContain(NOTES);
	});

	it('writes a file for a release with no members', async () => {
		// Extension 1a, and the screen `renderScope` returns early from — reachable only
		// because the actions area is drawn above that return.
		const { view, vault } = releaseScreen({ status: 'Released' }, emptyReleaseVault(), NOTES_ON);

		await press(view, '.pbl-rel-notes');

		expect(vault.contents.get(NOTES)).toContain(en['release.notes.empty']);
	});

	// WHICH report catches which is asked in the domain suites, not here. Two of these
	// rows were labelled `membershipCollision` until each report was removed in turn and
	// watched: both are caught by `configProblems` too, because this view resolves the
	// plan's release key and its own membership key from ONE option, so a collision on it
	// is visible to both. `membershipCollision` is kept — it is the domain's rule and it
	// defends a write — but no test here isolates it, and the label no longer claims one
	// does. The other two rows ARE isolated: removing `configProblems` fails only the
	// first, and removing `releaseNoteProblems` fails only the second.
	it.each([
		['a state property on the order key (only configProblems)', { stateProperty: 'note.order' }],
		['a record that overwrites the plan (only releaseNoteProblems)', { releasedDateProperty: 'note.target-date' }],
		['a membership key on the type key', { membershipProperty: 'note.type' }],
		['a membership key on the tags key', { membershipProperty: 'note.tags' }],
	])('withholds generation for %s', (_name, override) => {
		const { view, vault } = releaseScreen({ status: 'Released' }, scopeVault(), { ...NOTES_ON, ...override });

		// The actions area itself must be on screen, or this assertion passes for the wrong
		// reason: a release whose screen never rendered has no button either.
		expect(view.viewEl.querySelector('.pbl-rel-actions')).not.toBeNull();
		expect(view.viewEl.querySelector('.pbl-rel-notes')).toBeNull();
		expect(view.viewEl.querySelector('.pbl-rel-actions-note')?.textContent).toContain('Fix the view options first');
		expect(vault.contents.get(NOTES)).toBeUndefined();
	});

	it('does NOT withhold it on the shipped default, where both views name one release key', () => {
		// The exemption is the default configuration, not an edge case.
		const { view } = releaseScreen({ status: 'Released' }, scopeVault(), NOTES_ON);
		expect(view.viewEl.querySelector('.pbl-rel-notes')).not.toBeNull();
	});

	it('names the folder to bind rather than only withholding the button', () => {
		const { view } = releaseScreen({ status: 'Released' }, scopeVault());
		expect(view.viewEl.querySelector('.pbl-rel-notes')).toBeNull();
		expect(view.viewEl.textContent).toContain(en['release.notes.bindFolder']);
	});

	it('leaves a valid generated file alone when membership is unbound', async () => {
		// The damage is the OVERWRITE, not the missing button, so the criterion is about
		// the file: every scope reads empty with the key unbound, and a file saying the
		// release contained nothing would replace one saying what shipped.
		// `In progress`, not `Released`: the point of the last assertion is that MARKING is
		// unaffected by an unbound membership key, and marking is withheld on a release
		// that is already out for its own reason.
		const { view, vault } = releaseScreen({ status: 'In progress' }, scopeVault(), {
			...NOTES_ON,
			membershipProperty: '',
		});
		await vault.app.vault.create(NOTES, `${markerFor('0.9.md')}\nwhat shipped\n`);

		expect(view.viewEl.querySelector('.pbl-rel-notes')).toBeNull();
		expect(view.viewEl.textContent).toContain(en['release.notes.bindMembership']);
		expect(vault.contents.get(NOTES)).toContain('what shipped');
		// Marking is still offered there: it reads the release note alone.
		expect(view.viewEl.querySelector('.pbl-rel-close')).not.toBeNull();
	});

	it('is disabled while a SIBLING view holds the write lock', () => {
		// Generation is not a frontmatter batch, so nothing else would stop it generating
		// from a membership that is about to change while `onDataUpdated` defers the
		// model rebuild.
		const { view, lock } = releaseScreen({ status: 'Released' }, scopeVault(), NOTES_ON);
		lock.applying = true;
		view.render();
		expect(button(view, '.pbl-rel-notes').hasAttribute('disabled')).toBe(true);
	});

	it('HOLDS the lock for the whole write, not just before it', async () => {
		// The disabled attribute and a `gate.writing` check both read the lock at an
		// instant. What this asserts is the window AFTER that: a sibling starting mid-write
		// would land this file from a membership that has since changed, and reading a
		// lock is not taking one.
		const { view, vault } = releaseScreen({ status: 'Released' }, scopeVault(), NOTES_ON);
		let heldDuringWrite = false;
		const create = vault.app.vault.create;
		vault.app.vault.create = async (path: string, data: string) => {
			heldDuringWrite = view.gate.writing;
			return create(path, data);
		};

		await press(view, '.pbl-rel-notes');

		expect(heldDuringWrite).toBe(true);
	});

	it('names the path it tried when the write fails', async () => {
		// The gate catches whatever its callback throws and reports a generic failure, so
		// a catch OUTSIDE it never runs — this asserts the notice the reader actually gets.
		const { view, vault } = releaseScreen({ status: 'Released' }, scopeVault(), NOTES_ON);
		vault.app.vault.create = async () => {
			throw new Error('write failed');
		};

		await press(view, '.pbl-rel-notes');

		expect(lastNotice()).toContain(NOTES);
		expect(lastNotice()).toBe(en['release.notes.failed'].replace('{path}', NOTES));
	});

	it('says so, and writes nothing, when the notes are already up to date', async () => {
		// A POPULATED release, built the way `writes the notes, and opens them` builds one:
		// `scopeVault()`'s own members name `R` while this helper opens `0.9`, so the default
		// generates the empty-release file — and byte-identical regeneration is a claim whose
		// whole risk lives in the body that file does not have. Grouping, ordering and the
		// per-member lines are what a second pass could reorder; an empty file cannot vary.
		const vault = scopeVault();
		vault.addFile('First PBI.md', { frontmatter: { type: 'PBI', release: '[[0.9]]', order: 1 } });
		vault.addFile('Second PBI.md', { frontmatter: { type: 'PBI', release: '[[0.9]]', order: 2 } });
		const { view } = releaseScreen({ status: 'Released' }, vault, NOTES_ON);
		await press(view, '.pbl-rel-notes');
		const first = vault.contents.get(NOTES);
		// The guard on the guard: with no members this read the empty-release sentence and the
		// comparison below still passed.
		expect(first).toContain('First PBI');
		expect(first).toContain('Second PBI');

		Notice.reset();
		await press(view, '.pbl-rel-notes');

		expect(vault.contents.get(NOTES)).toBe(first);
		expect(lastNotice()).toBe(en['release.notes.unchanged'].replace('{path}', NOTES));
	});

	it('refuses another release’s notes at the same output path', async () => {
		// Extension 4c, and the reason the marker gained a third part. Obsidian lets
		// `a/0.9.md` and `0.9.md` coexist, and the output path is built from the BASENAME,
		// so both want `notes/0.9 release notes.md`. The marker is what must tell them
		// apart — and only if it names the release by PATH: by NAME both markers are the
		// same string, the second generation reads as the first's regeneration, and the
		// notes this refusal exists to protect are silently overwritten.
		//
		// BOTH generations are driven rather than one planted. A planted file cannot see
		// this: whatever marker the fixture writes differs from the buggy spelling as well
		// as the correct one, so the test passed with `release.name` in place — watched
		// doing exactly that before it was written this way.
		const { view, vault } = releaseScreen({ status: 'Released' }, twoReleasesOneBasename(), NOTES_ON);
		view.pick('a/0.9.md');
		await press(view, '.pbl-rel-notes');
		expect(vault.contents.get(NOTES)).toContain('A member');

		view.pick('0.9.md');
		Notice.reset();
		await press(view, '.pbl-rel-notes');

		expect(vault.contents.get(NOTES)).toContain('A member');
		expect(lastNotice()).toBe(en['release.notes.refused'].replace('{path}', NOTES));
	});
});
